id: fadf26615a5643f28391c002b17b8a04
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_431-The_Tantra_of_Candamaharosana-v1
  language: bo
  author: ''
  volume: {}
